### ISSUE TITLE
Error crashing homebridge / API changed

### ISSUE THREAD

**Issue by davidt94** [tkleijkers/homebridge-visonic-powerlink3#5]
Hi,

I am getting the following error causing my homebridge to crash. is this something you can help with?

https://pastebin.com/EUiBymF1

many thanks!

**Comment by tkleijkers** [comment]
Hi @cjones813, it seems that the authentication request to Visonic failed. Are you sure you added the correct configuration and authentication details?

The error is thrown at parsing the response from Visonic:
https://github.com/tkleijkers/visonic-powerlink3/blob/eea8666d6abf60c852d2da572dc9c0bfb33185a5/index.js#L82

**Comment by davidt94** [comment]
Hi @tkleijkers, Yes I am sure its the correct config. Visonic have done an update to include 2 factor authentication, do you think this could be why?

**Comment by tkleijkers** [comment]
I indeed think that Visonic changed their API and thus the authentication flow should be corrected. I am not active on development on this project, so someone can make a pull-request to fix this or I may fix it in the future.

**Comment by davidt94** [comment]
Thanks for the reply. yes, I now need to enter a username and password on the VisonicGo app unfortunately. That is a shame, I would happily make a donation to anybody that is able to fix this 👍

Thanks!

**Comment by StuFull** [comment]
Same problem for me.  It seems Tyco has changed the way the login is managed.

I have had to log in to the app again.

**Comment by StuFull** [comment]
I don't know if it helps but I found this document

https://www.visonic.com/Data/Uploads/Alarm_Install_App_User_Guide_English_D_307194.pdf

**Comment by tkleijkers** [comment]
> I don't know if it helps but I found this document
> 
> https://www.visonic.com/Data/Uploads/Alarm_Install_App_User_Guide_English_D_307194.pdf

This is another app

**Comment by tkleijkers** [comment]
I based the API request on https://github.com/barcar/visonic_control. If someone knows how the new API works, I can update this package. However this API is not documented by Tyco / Visonic so someone has to sniff the request from the app to the API.

**Comment by curry756** [comment]
+1 for a fix.  I was hoping to get this working too.

**Comment by barcar** [comment]
> I based the API request on https://github.com/barcar/visonic_control. If someone knows how the new API works, I can update this package. However this API is not documented by Tyco / Visonic so someone has to sniff the request from the app to the API.

That's my project. I think they switched to SSL pinning so I couldn't sniff the traffic. 

I couldn't figure out what changed by myself but I think this person has... https://github.com/And3rsL/VisonicAlarm2. Their commits reference upgrading to API v8 which is what I see listed at https://visonic.tycomonitor.com/rest_api/version = so maybe there is hope.

**Comment by tkleijkers** [comment]
I updated the [visonic_powerlink3](https://github.com/tkleijkers/visonic-powerlink3) package to use the new REST API of Visonic. Please let me know if it works.

**Comment by barcar** [comment]
I'm getting this error when trying to install:

`No matching version found for visonic-powerlink3@^1.1.0.`

From what I can see  I've got 1.0.0 installed and can't see 1.1.0. Not an NPM expert so could be my stupidity.

**Comment by davidt94** [comment]
> 
> 
> I'm getting this error when trying to install:
> 
> `No matching version found for visonic-powerlink3@^1.1.0.`
> 
> From what I can see I've got 1.0.0 installed and can't see 1.1.0. Not an NPM expert so could be my stupidity.

Experiencing the same issue. Did you manage to get it installed?

**Comment by tkleijkers** [comment]
The updated version is not yet on npm. I did not publish the package to npm myself and asked the publisher to give me permission to update the package. You can however clone the git repository and link the package yourself for now.

**Comment by barcar** [comment]
> The updated version is not yet on npm. I did not publish the package to npm myself and asked the publisher to give me permission to update the package. You can however clone the git repository and link the package yourself for now.

I’m confused... when I look at https://github.com/tkleijkers/visonic-powerlink3 I don’t see any commits after v1.0.1 in July. Is there another repository?

**Comment by davidt94** [comment]
Thanks. I have managed to get it installed, but get the follow error once the config has been added.

https://pastebin.pl/view/16aae3c3

**Comment by barcar** [comment]
> I have managed to get it installed, but get the follow error

Me too.

**Comment by davidt94** [comment]
Seems as though 'homebridge-visonic-powerlink3' was updated, 'but visonic-powerlink3' wasn't. @tkleijkers Is this correct?

**Comment by tkleijkers** [comment]
My fault. Pushing the update to github failed and I didn't notice. https://github.com/tkleijkers/visonic-powerlink3 is now updated with the code to connect to the new API. Please notice to add your username and password in the config. I didn't test it myself in homebridge yet (didn't have the time).

**Comment by davidt94** [comment]
Many thanks! Successfully installed and no longer crashing homebridge. 

Added config including my username and password but then get the following error.

[Burglar Alarm] Executing request https://visonic.tycomonitor.com/rest_api/8.0/status
[Burglar Alarm] Updating status (1)
[Burglar Alarm] Error polling: Error: Error getting raw status: Error: Failed to get authentication session-token: Bad Request Params

**Comment by tkleijkers** [comment]
Looks like the user login succeeded but the login to the panel fails. Are the setting (panelWebName and userCode etc) correct? Maybe you can turn on debug:true to get some more logging.

**Comment by tkleijkers** [comment]
I missed the params in this package. They are added. I see now some other things which should be updated in the package. I will look into it when I have more time available.

**Comment by davidt94** [comment]
> 
> 
> I missed the params in this package. They are added. I see now some other things which should be updated in the package. I will look into it when I have more time available.

No problem. Many thanks for your time on this. Double checked all settings in the config and they are correct.

**Comment by barcar** [comment]
I checked my config and all looks ok. I'm seeing this in debug mode:

[10/21/2020, 10:20:54 PM] [Visonic] Initializing PowerLink3 accessory...
[10/21/2020, 10:20:54 PM] [Visonic] getCurrentState
[10/21/2020, 10:20:54 PM] [Visonic] Response from getUserToken HTTP call:
[10/21/2020, 10:20:54 PM] [Visonic] error: null
[10/21/2020, 10:20:54 PM] [Visonic] response:  {"statusCode":400,"body":{"error":10001,"error_message":"Bad Request Params","error_reason_code":"BadRequestParams","extras":[{"key":"email","value":"required"},{"key":"password","value":"required"}]},"headers":{"server":"nginx","date":"Wed, 21 Oct 2020 21:20:54 GMT","content-type":"application/json; charset=utf-8","transfer-encoding":"chunked","connection":"close","x-frame-options":"SAMEORIGIN","x-xss-protection":"1; mode=block","x-content-type-options":"nosniff"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"visonic.tycomonitor.com","port":443,"hostname":"visonic.tycomonitor.com","hash":null,"search":null,"query":null,"pathname":"/rest_api/8.0/auth","path":"/rest_api/8.0/auth","href":"https://visonic.tycomonitor.com/rest_api/8.0/auth"},"method":"POST","headers":{"Content-Type":"application/json","accept":"application/json","content-length":49}}}
[10/21/2020, 10:20:54 PM] [Visonic] body: {"error":10001,"error_message":"Bad Request Params","error_reason_code":"BadRequestParams","extras":[{"key":"email","value":"required"},{"key":"password","value":"required"}]}
[10/21/2020, 10:20:54 PM] [Visonic] Executing request https://visonic.tycomonitor.com/rest_api/8.0/status
[10/21/2020, 10:20:54 PM] [Visonic] Updating status (1)
[10/21/2020, 10:20:54 PM] [Visonic] Error polling: Error: Error getting raw status: Error: Failed to get authentication session-token: Bad Request Params`

**Comment by barcar** [comment]
> I see now some other things which should be updated in the package. I will look into it when I have more time available.

Thanks for your help.

**Comment by JSVarga** [comment]
I recently updated to the latest version, wasn't in a hurry as everything working apart from one small issue on automations getting fired on both Arm and Disarm despite conditions set in HomeKit. Updated and now it is crashing home bridge with the following message:
[11/3/2020, 7:11:05 AM] [Visonic Home Alarm] Updating status (1)
[11/3/2020, 7:11:05 AM] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /homebridge/node_modules/homebridge-visonic-powerlink3/node_modules/visonic-powerlink3/index.js:88:20
    at Request._callback (/homebridge/node_modules/homebridge-visonic-powerlink3/node_modules/visonic-powerlink3/index.js:309:5)
    at Request.self.callback (/homebridge/node_modules/homebridge-visonic-powerlink3/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-visonic-powerlink3/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-visonic-powerlink3/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
[11/3/2020, 7:11:05 AM] Got SIGTERM, shutting down Homebridge...

Is this the same issue? I there any way to install the previous version as these do not seem to be versioned in GitHub?

UPDATE: I've rolled back to V1.1 and V1 and still have the same problem. If I empty the config entries to minimum (accessory and name) then it runs but this is in the log (as above):
[11/3/2020, 8:57:25 AM] [Visonic Home Alarm] Executing request https://undefined/rest_api/8.0/status
[11/3/2020, 8:57:25 AM] [Visonic Home Alarm] Updating status (1)
[11/3/2020, 8:57:25 AM] [Visonic Home Alarm] Error polling: Error: Error getting raw status: Error: Failed to get authentication session-token: Error: ETIMEDOUT

This is my config details:
"accessory": "PowerLink3",
            "name": "Visonic Home Alarm",
            "host": "logonmysecurity.com",
            "userCode": "XXXX",
            "appType": "com.visonic.PowerMaxApp",
            "userId": "89b14b39-dbe1-4364-b3d8-6303b026b397",
            "panelWebName": "148e29”

Note this is running in Homebridge within a Docker container on a Synology NAS. The host does not provide userEmail our userPassword, only four digit code. Frustrating as was working fine until update.

**Comment by StuFull** [comment]
Has anyone had any success in getting this to work?

Thanks for your effort so far tkleijkers but I think we are still missing something.

**Comment by xEzeit** [comment]
> Has anyone had any success in getting this to work?
> 
> Yes don't work for me as well  :/
> 
> Thanks for your effort so far tkleijkers but I think we are still missing something.

**Comment by xEzeit** [comment]
> Has anyone had any success in getting this to work?
> 
> 
> 
> Thanks for your effort so far tkleijkers but I think we are still missing something. 

Yes don't work for me as well :/

**Comment by JSVarga** [comment]
Keep trying by putting the entries back into the config file and restart. Every time Homebridge fails and won't run, then delete from config and everything runs. Lots of other updates to other plugins without issue. Just frustrated because it was working.

**Comment by xEzeit** [comment]
> Keep trying by putting the entries back into the config file and restart. Every time Homebridge fails and won't run, then delete from config and everything runs. Lots of other updates to other plugins without issue. Just frustrated because it was working.

Ok but in Userid, i can put random guid ?

**Comment by tkleijkers** [comment]
I will have to look into it but don't have the time currently.

**Comment by xEzeit** [comment]
> I will have to look into it but don't have the time currently. 

Ok i wait the update, i look forward :)

**Comment by nitaybz** [comment]
@tkleijkers it seems like you are not passing the user ID and email to the powerlink3 lib...

EDIT: you've only added those to GitHub but not pushed to NPM.... no chance it will work

**Comment by nitaybz** [comment]
I created a pull request for both this plugin and it's visonic-powerlink3 library to fix what's caused it to break + small improvement.

**Comment by JSVarga** [comment]
> I created a pull request for both this plugin and it's visonic-powerlink3 library to fix what's caused it to break + small improvement.

Sounds promising, apologies if not up to speed but how do I install this update? Running Homebridge in Docker on Synology NAS but this does not show an update version. Does it need to be merged with main package?

**Comment by nitaybz** [comment]
yes it does

**Comment by StuFull** [comment]
Do you have this working now?

**Comment by JSVarga** [comment]
I am not sure how to install the pull request on my setup, through Homebridge UI I usually have an Update option.

**Comment by nitaybz** [comment]
you can't at the moment... the fix is both in this plugin and in the library it uses... the plugin owner will have to merge both my pull requests and push to NPM before you can use it

**Comment by JSVarga** [comment]
Understood, thanks for the update and what you have done.

**Comment by nitaybz** [comment]
I'm working now on setting one last improvement to improve the speed of the loading... at the moment getting the state will delay the entire homebridge until it is returned... fixing

**Comment by tkleijkers** [comment]
I will look at it today! 👍🏻 Thanks for the PR

**Comment by tkleijkers** [comment]
I published version 1.2.0 on NPM. If @nitaybz pushes an update I will publish this one as well. Many thanks to @nitaybz!

**Comment by nitaybz** [comment]
I already made all the changes needed... should be ok now, faster loading and no night mode in Home app

**Comment by tkleijkers** [comment]
Okay, it seems to work at my side. I will close this issue. Thanks again.

**Comment by JSVarga** [comment]
Sorry, still not working for me on my Synology NAS Docker installation. I tried uninstalling and reinstalling and did notice these errors:
USER: root
DIR: /homebridge
CMD: npm install --save homebridge-visonic-powerlink3@latest

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

Homebridge runs until I update the config with my details then it crashes Homebridge which won't run until I remove my config details.

**Comment by nitaybz** [comment]
can you post the logs?
this warning is not the issue

**Comment by JSVarga** [comment]
Sure, here is the log from the most recent attempt. You will see the SyntacError message just the the rest api all to the website.
[homebridge.log.txt](https://github.com/tkleijkers/homebridge-visonic-powerlink3/files/6003180/homebridge.log.txt)

**Comment by nitaybz** [comment]
I believe your configuration is wrong... probably the "host" part as it can't be reached... it should be left as in the example on the readme... don't change it to the device IP or anything like that...

**Comment by tkleijkers** [comment]
Indeed as @nitaybz mentions the host should be as in the example. Powerlink3 cannot be reached directly.

**Comment by JSVarga** [comment]
For the record the configuration was using the visonic website rather than Tyco as we do not have an Id and Password and that's what I read, just use the Panel Name. This is exactly the config that was working before, I saved it down.

I'll have a play with the config, I know Visonic is just a wrapper for Tyco may they have/haven't changed in sync with Tyco.

**Comment by tkleijkers** [comment]
You should install the Visonic app and follow the process to create a username and password. The old API will not work anymore in this latest version.

**Comment by JSVarga** [comment]
My Visonic-Go app only allows a PIN, no ability to set username and password. More investigation needed my end.

**Comment by davidt94** [comment]
@JSVarga You need to update the app. Once the app is updated, you can then set a username and password 👍

**Comment by JSVarga** [comment]
> @JSVarga You need to update the app. Once the app is updated, you can then set a username and password 👍

I think I have discovered it is related to the security provider. Mine is using a host with the address of logonmysecurity.com, which is probably their own wrapper, and I set this in the app (which is up to date from App Store). It only asks me for a PIN.

I updated the Host to visonic.tycomonitor.com and it then asked for an email address, so I registered and set a password. All good until I tried to connect my panel. Got the Panel serial number from the box but it won't accept my user code.

Going to contact my security provider and take it further, I suspect they haven't updated their host, but it appears this is not an issue with the plug in. Thanks all for your help.

**Comment by davidt94** [comment]
> > @JSVarga You need to update the app. Once the app is updated, you can then set a username and password 👍
> 
> 
> 
> I think I have discovered it is related to the security provider. Mine is using a host with the address of logonmysecurity.com, which is probably their own wrapper, and I set this in the app (which is up to date from App Store). It only asks me for a PIN.
> 
> 
> 
> I updated the Host to visonic.tycomonitor.com and it then asked for an email address, so I registered and set a password. All good until I tried to connect my panel. Got the Panel serial number from the box but it won't accept my user code.
> 
> 
> 
> Going to contact my security provider and take it further, I suspect they haven't updated their host, but it appears this is not an issue with the plug in. Thanks all for your help.

Ahh yes, you are correct. Your provider is using an older version of the server.

They will need to get this updated ASAP. The next update to the Visonic-Go app is going to kill that old protocol altogether, you would then loose access to the app completely.

The reason why you can't access via visonic.tycomonitor.com is because your panel is not registered on that server. You need to enter the IP address of the visonic server into your panel for this to work. You would then be registered on the visonic server.

You have 2 options while you wait for your service provider to update their server; Either use an older version on this plugin or start using the visonic server.

Hope this helps.

**Comment by JSVarga** [comment]
Thanks @cjones813 Given they provide me with remote monitoring I don't think using the visonic server is an option, and I originally tried reverting to previous versions of the plug-in when the problem first occurred and that didn't help.

Interesting info on the new app version will render the current access useless, it will help me to press them into upgrading their servers.

**Comment by davidt94** [comment]
@JSVarga Ahh thats a problem. I would definitely push them on that. The latest server update fixed a huge security flaw that was discovered. This update also added 2 factor authentication making it even more secure.

If you drop back to version 1.0.0 that should solve your issue. That should still use the old protocol.

**Comment by StuFull** [comment]
@JSVarga you can configure the panel to use the tyco server and cut out the monitoring company, unless you specifically want 3rd party monitoring.

**Comment by StuFull** [comment]
You’ll need installer access to the panel (if you don’t have it then it’s more complicated as you need to ‘default’ the panel to factory reset). 

Set the server IP (IP Reciever) to 052.058.105.181
Server name is visonic.tycomonitor.com

**Comment by sagistn** [comment]
Updated to the latest, still can't get it to work. I think I'm missing something in the configuration. Does anyone has an idea what's the issue here?
**Config:**
"accessory": "PowerLink3",
    "name": "Alarm",
    "host": "visonic.tycomonitor.com",
    "userCode": "1234",
    "debug": true,
    "appType": "com.visonic.PowerMaxApp",
    "userId": "sagi",
    "panelWebName": "xxxxx",
    "userEmail": "mymail@gmail.com",
    "userPassword": "xxxx"

**Debug log:**
[24/02/2021, 19:34:43] [Alarm] Error polling: Error: Error getting raw status: Error: Failed to get authentication session-token: Bad Request Params
[24/02/2021, 19:35:13] [Alarm] getCurrentState
[24/02/2021, 19:35:13] [Alarm] Response from getUserToken HTTP call:
[24/02/2021, 19:35:13] [Alarm] error: null
[24/02/2021, 19:35:13] [Alarm] response:  {"statusCode":200,"body":{"user_token":"439ab58e-3857-44e1-9f0e-4d957408e15b"},"headers":{"server":"nginx","date":"Wed, 24 Feb 2021 17:35:13 GMT","content-type":"application/json; charset=utf-8","transfer-encoding":"chunked","connection":"close","x-frame-options":"SAMEORIGIN, SAMEORIGIN","x-xss-protection":"1; mode=block, 1; mode=block","x-content-type-options":"nosniff, nosniff","content-security-policy":"default-src 'self'; style-src 'self' 'unsafe-inline' https://*.googleapis.com; font-src 'self' data: https:; connect-src 'self' ws://visonic.tycomonitor.com wss://visonic.tycomonitor.com; script-src 'self' https://*.google.com https://*.googleapis.com 'unsafe-inline' 'unsafe-eval'; img-src 'self' data: https://*.gstatic.com https://*.google.com","strict-transport-security":"max-age=31536000"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"visonic.tycomonitor.com","port":443,"hostname":"visonic.tycomonitor.com","hash":null,"search":null,"query":null,"pathname":"/rest_api/8.0/auth","path":"/rest_api/8.0/auth","href":"https://visonic.tycomonitor.com/rest_api/8.0/auth"},"method":"POST","headers":{"Content-Type":"application/json","accept":"application/json","content-length":71}}}
[24/02/2021, 19:35:13] [Alarm] body: {"user_token":"439ab58e-3857-44e1-9f0e-4d957408e15b"}
[24/02/2021, 19:35:13] [Alarm] Got user-token: 439ab58e-3857-44e1-9f0e-4d957408e15b
[24/02/2021, 19:35:14] [Alarm] Response from getSessionToken HTTP call:
[24/02/2021, 19:35:14] [Alarm] error: null
[24/02/2021, 19:35:14] [Alarm] response:  {"statusCode":400,"body":{"error":10001,"error_message":"Bad Request Params","error_reason_code":"BadRequestParams","extras":[{"key":"panel_serial","value":"incorrect"}]},"headers":{"server":"nginx","date":"Wed, 24 Feb 2021 17:35:13 GMT","content-type":"application/json; charset=utf-8","transfer-encoding":"chunked","connection":"close","x-frame-options":"SAMEORIGIN","x-xss-protection":"1; mode=block","x-content-type-options":"nosniff"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"visonic.tycomonitor.com","port":443,"hostname":"visonic.tycomonitor.com","hash":null,"search":null,"query":null,"pathname":"/rest_api/8.0/panel/login","path":"/rest_api/8.0/panel/login","href":"https://visonic.tycomonitor.com/rest_api/8.0/panel/login"},"method":"POST","headers":{"Content-Type":"application/json","User-Token":"439ab58e-3857-44e1-9f0e-4d957408e15b","accept":"application/json","content-length":97}}}
[24/02/2021, 19:35:14] [Alarm] body: {"error":10001,"error_message":"Bad Request Params","error_reason_code":"BadRequestParams","extras":[{"key":"panel_serial","value":"incorrect"}]}
[24/02/2021, 19:35:14] [Alarm] Updating status (1)
[24/02/2021, 19:35:14] [Alarm] Error polling: Error: Error getting raw status: Error: Failed to get authentication session-token: Bad Request Params

**Comment by nitaybz** [comment]
@sagistn the answer is in the logs:
[{"key":"panel_serial","value":"incorrect"}]}

the panelWebName you entered is incorrect...

**Comment by sagistn** [comment]
Thx for the prompt reply :)
Isn't the panelWebName the panel's serial number?

**Comment by nitaybz** [comment]
@sagistn nope... it's in the app written under the "alarm system" name...
numbers and letters like this: 123AB3

**Comment by sagistn** [comment]
Yes, that's what I put in... Just noticed it is case sensitive.
Finally it works! thx

**Comment by JSVarga** [comment]
> @JSVarga Ahh thats a problem. I would definitely push them on that. The latest server update fixed a huge security flaw that was discovered. This update also added 2 factor authentication making it even more secure.
> 
> If you drop back to version 1.0.0 that should solve your issue. That should still use the old protocol.

Sorry for the delay in responding, few other things going on and trouble getting through to security monitoring company. Helpdesk unsurprisingly didn't know what I was talking about but got put through to technical manager however took a few moments to get on the same page. He then explained they were experience issues with the update and many clients that they had to work through so the upgrade was going to take some time. Have to say I wasn't entirely convinced and he wouldn't give me a timeline. Might contact Visonic/Tyco directly to ask them.

On the second point I have reverted to V1.0.0, and even uninstalled and reinstalled, but can't get it to work again like it did. Don't know if that is related to other updates in Homebridge itself.
